### PR TITLE
Add HL7 France package-feed

### PR DESCRIPTION
**Pull request by nriss**
Note that hl7.fhir.fr.core has already been published using simplifier in previous versions. Is it a problem ?

FYI @wardweistra

### CODE REVIEW

**Comment by wardweistra** [comment]
@nriss Please note that your feed has two major issues: https://www.rssboard.org/rss-validator/check.cgi?url=https://hl7.fr/ig/fhir/package-feed.xml

**Comment by nriss** [comment]
Thank you for identifying the bug @wardweistra! And @ypoiron for updating the website :)

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by wardweistra** [comment]
@nriss We've made sure you can now publish to `hl7.fhir.fr.core` from outside feeds. However, your feed is still a mess ;)

Keep monitoring the output in this channel: https://chat.fhir.org/#narrow/stream/328836-tooling.2FPackage-Crawlers/topic/stream.20events/near/429589125

**Comment by nriss** [comment]
Great! Thanks a lot @wardweistra!
The package-feed has been corrected [there](https://github.com/Interop-Sante/IG-website-release/blob/main/www/ig/fhir/package-feed.xml) but has not been published yet, it will be corrected during the week :)

Didn't know about this stream! Really interesting! Thanks

**Pull request merged**
