### PR TITLE
Add SMART Guidelines DDCC

### PR DESCRIPTION
**Pull request by costateixeira**
@ritikarawlani @litlfred can you please confirm this PR to support DDCC?

### CODE REVIEW

**Comment by ritikarawlani** [comment]
Looks good, confirmed

**Comment by costateixeira** [comment]
@grahamegrieve can you please merge?

**Review by litlfred — APPROVED** [review]
Looks good

**Comment by ritikarawlani** [comment]
@grahamegrieve  Could you please merge?

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
