### PR TITLE
finally adding FUT DK to the list

### PR DESCRIPTION
**Pull request by jkiddo**

### CODE REVIEW

**Comment by jkiddo** [comment]
@grahamegrieve I merged latest into my fork and the checks that fail are caused by entries that are already part of the main fork 🤔

**Comment by jkiddo** [comment]
@grahamegrieve its your own commit that reintroduced those unwanted unicode characters in https://github.com/FHIR/ig-registry/commit/b3f10c49ab94167b4d432486b44cb7cc2adae219

**Review by grahamegrieve — APPROVED** [review]
ok

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
made the same change in master because of conflicts

**Pull request closed without merging**
