### PR TITLE
Entry for hl7.se Swedish base FHIR profiles

### PR DESCRIPTION
**Pull request by peturv**
Created publication 1.0.0 of swedish base profiles.

### CODE REVIEW

**Review by grahamegrieve — CHANGES_REQUESTED** [review]
this entry needs values for description, authority, and country. If you're not clear what these should be, ask on https://chat.fhir.org/#narrow/stream/179252-IG-creation

**Comment by peturv** [comment]
> this entry needs values for description, authority, and country. If you're not clear what these should be, ask on https://chat.fhir.org/#narrow/stream/179252-IG-creation

Sorry about that. Added missing information and updated PR. I have an outstanding question in Zulip on authority (HL7 vs HL7 Sweden), will update/change if needed as soon as I get a response.

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by vadi2** [comment]
Is this good to be merged?

**Pull request merged**
