### PR TITLE
Add GKL ig-tooling

### PR DESCRIPTION
**Pull request by gabriel0316**

### CODE REVIEW

**Comment by gabriel0316** [comment]
@grahamegrieve

**Comment by grahamegrieve** [comment]
how is this a national base specification?

**Comment by gabriel0316** [comment]
True - was simply the first category I saw somewhere else. Maybe `Research` fits better. If OK for you, I will change it to that.

**Comment by grahamegrieve** [comment]
yes change to that

**Comment by grahamegrieve** [comment]
Also, remove authority, set country to 'at', and provide a description

**Comment by gabriel0316** [comment]
@grahamegrieve now it should fit

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
