### PR TITLE
Updating with latest published danish municipality terminology

### PR DESCRIPTION
**Pull request by jkiddo**

### CODE REVIEW

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
Going to mark this as not draft?

**Comment by jkiddo** [comment]
Eventually, yes

**Comment by jkiddo** [comment]
@Kirstinerosenbeck are you good with this?

**Comment by grahamegrieve** [comment]
This needs a description

**Comment by Kirstinerosenbeck** [comment]
Looks good to me. I am not sure what needs a description and where, but we will be happy to provide one. We have made a new version of kl-term. Other than that, we are in a process of cleaning up ci-build paths, so that it works more consistently with each new release. Sorry if it causes problems.

**Comment by grahamegrieve** [comment]
I thought I saw a description missing, but not now

**Comment by jkiddo** [comment]
@grahamegrieve its ready to be merged when you are

**Comment by jkiddo** [comment]
@grahamegrieve ?

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
