### PR TITLE
Updating with the danish FUT ehealth telemedicine release 3.2.0

### PR DESCRIPTION
**Pull request by jkiddo**

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
I'm not going to accept a commit that moves other people's content

**Comment by jkiddo** [comment]
ehmmmm .... it does not move other peoples content. Where do you see that. It moves 'my' own content.

**Comment by grahamegrieve** [comment]
weird. it showed me lots of content being removed. Doesn't now

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
